name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: keisisqrl/wpull
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Login to docker hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_ACCESS }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}